import { useEffect, useRef } from 'react';
import { flushSync } from 'react-dom';
import { methods } from './content.js';
import { questionsFor, changeAnswer, recommend, answerSummary, validateAnswers } from './chooser.js';
import { Prompt } from './Common.jsx';
export default function Chooser({answers,setAnswers}){
 const latest=useRef(answers);latest.current=answers;
 const result=recommend(answers);
 useEffect(()=>{
  const context=document.modelContext;if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const register=tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(e=>console.warn('WebMCP registration unavailable',e));}catch(e){console.warn('WebMCP registration unavailable',e);}};
  const properties=Object.fromEntries(['response','goal','outcome','dependency','groups','exploration','format','association','preference','pairIndependent'].map(key=>[key,{type:'string'}]));
  register({name:'configure_analysis_choices',title:'解析の検討条件を設定',description:'統計解析の選択フォームを、表示と同じ分岐ルールで更新します。回答は先頭から順に指定し、無効な組み合わせは拒否します。空の回答はリセットです。現在の質問と選択肢は get_analysis_choices で確認できます。',inputSchema:{type:'object',properties:{answers:{type:'object',properties,additionalProperties:false}},required:['answers'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||Object.keys(input).some(k=>k!=='answers'))throw new Error('answers のみ指定してください。');const valid=validateAnswers(input.answers);flushSync(()=>setAnswers(valid));return {answers:valid,...recommend(valid)};}});
  register({name:'get_analysis_choices',title:'解析の検討条件と候補を読む',description:'画面に表示中の条件、次の質問の選択肢、候補の理由を読みます。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||Object.keys(input).length)throw new Error('入力は空のオブジェクトです。');return {answers:latest.current,questions:questionsFor(latest.current),...recommend(latest.current)};}});
  return()=>lifecycle.abort();
 },[]);
 return <><p className="eyebrow">03 / 条件から候補を考える</p><h1>どの解析を使う？</h1><p className="lede">問いとデータを整理しながら、手法の候補を絞ってみましょう。選択肢を変えると、候補と理由も変わります。</p><p className="note">用語に迷ったら、<a href="#/statistics/variables">目的変数・説明変数とデータの種類</a>を確認できます。ここで出るのは、詳しく検討するための候補です。</p><div className="chooser-layout"><div className="questions">{questionsFor(answers).map((q,i)=><fieldset key={q.key}><legend><span className="course-no">0{i+1}</span>{q.title}</legend><p id={`help-${q.key}`} className="question-help">{q.help}</p><div className="option-list">{q.options.map(o=><label className={answers[q.key]===o.value?'selected':''} key={o.value}><input type="radio" name={q.key} value={o.value} checked={answers[q.key]===o.value} onChange={()=>setAnswers(changeAnswer(answers,q.key,o.value))} aria-describedby={`help-${q.key}`}/><span>{o.label}</span></label>)}</div></fieldset>)}<button className="reset-button" onClick={()=>setAnswers({})}>選択をリセット</button></div><section className="candidates" aria-label="解析の候補"><p className="eyebrow">ここから検討する</p><h2>候補と、その理由</h2><p role="status" className="candidate-intro">{result.intro}</p>{result.candidates.map((c,i)=>{const m=methods.find(m=>m.id===c.id);return <article className="candidate" key={`${c.id}-${i}`}><h3>{c.variant||m.name}</h3><p>{c.reason}</p><dl><dt>得られるもの</dt><dd>{c.variant?.includes('追加検討')?'モデルにより異なります。下の解説を入口に、ここで挙げた派生手法の出力と前提を確認してください。':m.output}</dd><dt>次に確かめること</dt><dd>{c.check}</dd></dl><a href={`#/statistics/method/${m.id}`}>{c.variant?`${m.name}の解説へ`:'この手法を読む'} →</a></article>;})}{!Object.keys(answers).length&&<p className="candidate-example">例えば、<br/>目的変数あり → 条件の比較 → 操作時間 → 同じ人で2条件<br/>なら「対応のあるt検定」が候補になります。</p>}</section></div>{Object.keys(answers).length>0&&<Prompt text={`以下の条件で、研究の解析計画を検討しています。\n${answerSummary(answers)}\n知りたいこと：【自分の問いを記入】\nデータの列と値の例・件数：【記入】\n候補：${result.candidates.map(c=>c.variant||methods.find(m=>m.id===c.id).name).join('、')||'未確定'}\nこの選択が問いに合っているか、どの条件が未確認かを一緒に考えてください。異なる候補は「答える問い」と「必要なデータ」の違いで比較してください。不足情報は質問し、まだコードは書かないでください。`}/>}<p className="small-note">生存時間、時系列、複雑な欠測、多数の目的変数など、この入口だけでは扱いきれない設計もあります。候補の解説と出典に戻り、必要に応じて専門家に相談してください。</p></>;
}
